spring:
  application:
    name: LoanApp
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
application:
  security:
    sign-up-path: /api/v1/sign-up
    sign-in-path: /api/v1/sign-in
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 900000 # 15 mins

logging:
  level:
    com.bb: DEBUG

loan-restrictions:
  allowed-number-of-installments: [6,9,12,24]
  allowed-interest-rate-range:
    lower-bound: 0.1
    upper-bound: 0.5

installment-payment-restrictions:
  number-of-maximum-due-months-to-pay: 3
  reward-penalty-rate: 0.001

